version: 2.1
orbs:
  python: circleci/python@4.0.0
jobs:
  pypi_publish:
    executor:
      name: python/default
      tag: '3.14'
    steps:
      - checkout
      - python/dist:
          build-tool: build
      - run: pip install twine && twine upload dist/*
workflows:
  main:
    jobs:
      - pypi_publish:
          filters:
            branches:
              only:
                - master
